[package]
name = "slaymumanager"
version = "1.8.0"
description = "Slay the Spire 2 Mod Manager"
authors = []
edition = "2024"
rust-version = "1.96.0"

[lib]
name = "slaymumanager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = [] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = { version = "0.4.44", features = ["serde"] }
thiserror = "2.0.18"
uuid = { version = "1.23.1", features = ["serde", "v4"] }
rfd = "0.17.2"
zip = "8.6.0"
sevenz-rust = "0.6.1"
reqwest = { version = "0.13.3", features = ["blocking", "json", "socks"] }
dirs-next = "2.0.0"
winreg = "0.56.0"
sha1 = "0.11.0"
notify = { version = "8.2.0", default-features = false, features = ["macos_fsevent"] }
lru = "0.18.0"
rars = "0.1.0"
steamworks = { version = "0.13.1", features = ["serde"] }
