[package]
name = "slaymumanager"
version = "1.0.0"
description = "Slay the Spire 2 Mod Manager"
authors = []
edition = "2021"
rust-version = "1.88"

[lib]
name = "slaymumanager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
uuid = { version = "1", features = ["serde", "v4"] }
rfd = "0.17"
zip = "8"
sevenz-rust = "0.6"
infer = "0.19"
reqwest = { version = "0.13", features = ["blocking", "json", "socks"] }
dirs-next = "2.0"
winreg = "0.56"
sha1 = "0.11"
filetime = "0.2"
notify = { version = "8", default-features = false, features = ["macos_fsevent"] }
